version: '3.7'

networks:
  test-network:

services:
  test-api:
    build: .
    container_name: test-api
    hostname: test-api
    networks:
      test-network:
        aliases:
          - test-api
  nginx:
    image: nginx:stable-alpine
    container_name: test-nginx
    hostname: test-nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server.crt:/etc/nginx/server.crt:ro
      - ./server.key:/etc/nginx/server.key:ro
    networks:
      test-network:
        aliases:
          - test-nginx
    ports:
      - 80:80
      - 443:443
